name: MSBuild

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types:
      - published

env:
  # Path to the solution file relative to the root of the project.
  SOLUTION_FILE_PATH: src/Native.sln

  # Configuration type to build.
  # You can convert this to a build matrix if you need coverage of multiple configuration types.
  # https://docs.github.com/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
  BUILD_CONFIGURATION: Release
  
  BUILD_PLATFORM: x64

permissions:
  contents: read

jobs:  
  build:
    name: ${{ matrix.os }}-${{ github.workflow }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
    - uses: actions/checkout@v3    
    - uses: lukka/get-cmake@latest

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Restore artifacts, or setup vcpkg for building artifacts
      uses: lukka/run-vcpkg@v10
      id: runvcpkg
      with:
        # This one is not needed, as it is the default value anyway.
        # vcpkgDirectory: '${{ github.workspace }}/vcpkg'
        vcpkgJsonGlob: '${{ github.workspace }}/src/vcpkg.json'      

    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      # Add additional options to the MSBuild command line here (like platform or verbosity level).
      # See https://docs.microsoft.com/visualstudio/msbuild/msbuild-command-line-reference
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} /p:Platform=${{env.BUILD_PLATFORM}} ${{env.SOLUTION_FILE_PATH}}
